version: 'build #{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  NATIVE_TOOLCHAIN: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
  BASH_INTERPRETER: C:\msys64\bin\bash.exe
  JAVA_OPTS: "-Xmx2048M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512M"
  RADLE_OPTS: "-Dorg.gradle.daemon=true"

build_script:
  - gradlew --info --stacktrace buildNativeProjects generateInterops build